import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import {Footer} from "@/components/Footer/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

async function getFooterHtml() {
    const data = await fetch("https://www.autodesk.com/content/experience-fragments/autodesk/en/universal-footer/master.content.html"
        , {cache: "force-cache"})
    return await data.text();
}

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const footerHtml = await getFooterHtml();
    return (
        <html lang="en">
        <body>
        {children}
        <Footer htmlContent={footerHtml}/>
        </body>
        </html>
    );
}
