import type { Metadata } from 'next';
import '@/app/globals.css';
import { Footer } from '@/components/Footer/Footer';
import LoaderComponent from '@/components/LoaderComponent/LoaderComponent';
import React, { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
